version: '3.3'

services:
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: 'pocapi'
      MYSQL_USER: 'springuser'
      MYSQL_PASSWORD: 'springuser'
      MYSQL_ROOT_PASSWORD: 'nicorego'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data/mysql:/var/lib/mysql

  app:
    image: pocapi
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '9090:9090'
    expose:
      - '9090'
    depends_on:
      - db
